default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: yourpassword

development:
  <<: *default
  database: hackdiem_development
 
test:
  <<: *default
  database: hackdiem_test

production:
  <<: *default
  database: hackdiem_production
